version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
      - '5900:5900'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
