services:
 postgres:
  container_name: postgres
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: keycloak
   POSTGRES_USER: keycloak
   POSTGRES_PASSWORD: localpassword
  volumes:
   - postgres_data:/var/lib/postgresql/data
 keycloak:
  container_name: keycloak
  image: quay.io/keycloak/keycloak:latest
  restart: always
  environment:
   KC_DB: postgres
   KC_DB_URL_HOST: postgres
   KC_DB_URL_DATABASE: keycloak
   KC_bB_USERNAME: keycloak
   KC_DB_PASSWORD: localpassword
   KC_HOSTNAME_URL: https://YOURFQDN
   KC_HOSTNAME_STRICT_HTTPS: "true"
   KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
   KC_PROXY: edge
   KEYCLOAK_ADMIN: admin
   KEYCLOAK_ADMIN_PASSWORD: YOURPASSWORD
   KEYCLOAK_FRONTEND_URL: https://YOURFQDN/auth
  ports:
   - 8443:8443
   - 8080:8080
  networks:
   - keycloak-auth
  depends_on:
   - postgres
  command: start
