services:
  app:
  image: 'portainer/portainer-ee:latest'
  restart: unless stopped
  ports:
  - '8000:8000'
  - '9443:9443'
  volumes:
  - ./portainer_data:/data
  - /var/run/docker.sock:/var/run/docker.sock
